Repository Brainketunze/restful-courses, pull requests merged in 2021-02, with the labels that each got.

#13 app-put
  index.js
Labels: update courses

#16 index.js delete
  courses.json
  index.js
  package.json
Labels: delete-course

#18 ready for Heroku
  package.json
  public/index.js
Labels: deployed
